# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_auto_20170823_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='article',
            name='picurl',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='article',
            name='type',
        ),
    ]
