# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 02:55
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_auto_20170829_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
