# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0008_auto_20170829_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_list',
            field=jsonfield.fields.JSONField(blank=True, default=dict, verbose_name='图片列表'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_list',
            field=jsonfield.fields.JSONField(blank=True, default=dict, verbose_name='视频列表'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
