# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0011_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='picurl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
