# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0012_auto_20170902_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='owner',
        ),
    ]
